# Generated by Django 5.2 on 2025-05-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0002_ingredient_default_unit_ingredient_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='default_quantity',
            field=models.FloatField(default=1.0),
        ),
    ]
