# Generated by Django 5.2 on 2025-05-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='default_unit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
