# Generated by Django 5.2 on 2025-05-12 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0003_ingredient_default_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='default_quantity',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='default_unit',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='image_url',
        ),
    ]
