# Generated by Django 5.2 on 2025-05-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0005_remove_ingredient_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='image',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pantryitem',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
