# Generated by Django 5.2 on 2025-05-18 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0006_remove_ingredient_image_ingredient_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pantryitem',
            name='image',
        ),
    ]
