# Generated by Django 5.2 on 2025-06-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0008_savedrecipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Snack1', 'Snack - 1'), ('Lunch', 'Lunch'), ('Snack2', 'Snack - 2'), ('Dinner', 'Dinner')], max_length=10)),
                ('day', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3)),
                ('food', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
