# Generated by Django 5.2 on 2025-06-14 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0009_mealplan'),
        ('pantry', '0009_reciperating'),
    ]

    operations = [
    ]
